apiVersion: v1
kind: ConfigMap
metadata:
  name: seed-config
data:
  genesis.json: {{ .Values.common.genesis }}
  node_key.json: {{ .Values.seed.node_key }}
  priv_validator_key.json: {{ .Values.seed.priv_key }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seed-data
data:
  priv_validator_state.json: |-
    {
      "height": "0",
      "round": 0,
      "step": 0
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-config
data:
  app.toml: |-
    {{ .Files.Get "app.toml" | indent 4 }}
