apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mycel-seed
spec:
  selector:
    matchLabels:
      app: mycel-seed
  serviceName: "mycel-seed"
  replicas: 1
  template:
    metadata:
      labels:
        app: mycel-seed
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mycel
        image: {{ .Values.common.image }}
        volumeMounts:
        - name: seed-volume
          mountPath: /opt/data
        ports:
          - containerPort: 1317
            name: api
          - containerPort: 8080
            name: rosetta
          - containerPort: 9090
            name: grpc
          - containerPort: 26657
            name: rpc
          - containerPort: 9091
            name: grpc-web
        command:
          - sh
          - -c
          - |
            {{ .Values.common.binaryName }} start --home /opt/data/mycel
      initContainers:
      - name: init-seed
        image: golang
        volumeMounts:
        - name: seed-volume
          mountPath: /opt/data
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 10Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 10Gi
            memory: 2Gi
        command:
          - bash
          - -cx
          - |
            if [ -d /opt/data/mycel ]; then
              exit 0;
            fi
            curl 'https://get.ignite.com/cli@'{{ .Values.ignite.version }}! | bash
            mkdir work
            cd work
            git clone {{ .Values.seed.repositoryURL }} .
            ignite chain init --home /opt/data/mycel
      volumes:
        - name: seed-volume
          persistentVolumeClaim:
            claimName: seed-volume

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mycel-node
spec:
  selector:
    matchLabels:
      app: mycel-node
  serviceName: "mycel-node"
  replicas: {{ .Values.node.replicas }}
  template:
    metadata:
      labels:
        app: mycel-node
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mycel
        image: {{ .Values.common.image }}
        volumeMounts:
        - name: data
          mountPath: /opt/data
        ports:
          - containerPort: 1317
            name: api
          - containerPort: 8080
            name: rosetta
          - containerPort: 9090
            name: grpc
          - containerPort: 26657
            name: rpc
          - containerPort: 9091
            name: grpc-web
        command:
          - sh
          - -c
          - |
            myceld start --home /opt/data/mycel
      initContainers:
      - name: init-node
        image: {{ .Values.common.image }}
        volumeMounts:
        - name: data
          mountPath: /opt/data
        - name: seed-volume
          mountPath: /opt/genesis
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 10Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 10Gi
            memory: 2Gi
        command:
          - bash
          - -cx
          - |
            if [ -d /opt/data/mycel ]; then
              exit 0;
            fi
            apt install -y jq
            myceld init node --home /opt/data/mycel
            cp /opt/genesis/mycel/config/genesis.json /opt/data/mycel/config/genesis.json
            SEED_NODE_ID=$(curl http://mycel-seed:26657/status | jq -r '.result.node_info.id')
            sed -i "s/persistent_peers = \"\"/persistent_peers = \"${SEED_NODE_ID}@mycel-seed:26656\"/g" /opt/data/mycel/config/config.toml
      volumes:
        - name: seed-volume
          persistentVolumeClaim:
            claimName: seed-volume

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.node.volumeSize }}

